pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'main',
                        credentialsId: 'Credential ID',
                        url: 'https://github.com/pdevix/Demo.git'
                }
            }
        }
	stage('Install dependencies') {
            steps {
                // Install Python dependencies
                sh 'pip install -r requirements.txt'
            }
        }
	stage('Test') {
            steps {
                script { // Your build commands go here 
	          sh "chmod +x -R ${env.WORKSPACE}" 
		  sh '/usr/bin/python3 /var/lib/jenkins/workspace/Inference_Demo/TF_Inference_cifar.py'
		  sh "echo ${currentBuild.number}"
	       }
            }
        }
	stage('Archive Artifacts') {
            steps {
                // Archive the artifacts (output files) generated by your script
                archiveArtifacts artifacts: '*'
            }
        }
}
}
